application:
  name: alfred-worldviews-app

labels:
  app: alfred-worldviews-app

namespace: alfred 

image:
  repository: linsay1999/worldviews-app
  tag: latest
  #pullPolicy: IfNotPresent
   
replicaCount: 3

#updateStrategy:
#  type: RollingUpdate
#  rollingUpdate: {}

#resources:
  ## Example:
  ## limits:::
  ##    cpu: 100m
  ##    memory: 128Mi
 # limits: {}
  ## Examples:
  ## requests:
  ##    cpu: 100m
  ##    memory: 128Mi

livenessProbe:
  enabled: false
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: false
  initialDelaySeconds: 5
  timeoutSeconds: 3
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1

autoscaling:
  enabled: false
  minReplicas: ""
  maxReplicas: ""
  targetCPU: ""
  targetMemory: ""
 
service:
  name: alfred-worldviews-svc
  type: LoadBalancer
  #protocol: "TCP"
  ports: 
    port: 3240
    nodePorts: 30014
    targetPort: 80
    containerport: 80

