apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfred-worldviews-app
spec:
  selector:
    matchLabels:
      app: alfred-worldviews-app
  replicas: 3
  template:
    metadata:
      labels:
        app: alfred-worldviews-app
    spec:
      containers:
      - name: alfred-worldviews-app
        image: linsay1999/worldviews-app:latest
        ports:
        - containerPort: 80
