apiVersion: v1
kind: Service
metadata:
  name: alfred-worldviews-svc
spec:
  type: LoadBalancer
  selector:
    app: alfred-worldviews-app
  ports:
    - protocol: "TCP"
      port: 3200
      targetPort: 80
      nodePort: 30014

